CREATE TABLE TOPPING
	(Name			VARCHAR(20)		NOT NULL
	Inventory		INT
	Price			Decimal(10,2) FIXME
	Cost			Decimal(10,2) FIXME
	Personal_Amt	Decimal(10,2) FIXME
	Medium_Amt		Decimal(10,2) FIXME
	Large_Amt		Decimal(10,2) FIXME
	XLarge_Amt		Decimal(10,2) FIXME
	CONSTRAINT TOPPK
		PRIMARY KEY(Name)
	);

CREATE TABLE PIZZA

CREATE TABLE CONTAINS

CREATE TABLE BASE_PRICE

CREATE TABLE ORDER

CREATE TABLE CUSTOMER

CREATE TABLE PICK_UP

CREATE TABLE DELIVERY

CREATE TABLE DINE_IN

CREATE TABLE SEAT_NUM

CREATE TABLE DISCOUNT

CREATE TABLE PERCENTAGE

CREATE TABLE DOLLAR_AMOUNT

CREATE TABLE APPLIES_PIZZA

CREATE TABLE APPLIES_ORDER
